# docker run --group-add 0 --group-add 1001 \
# -v /var/run/docker.sock:/var/run/docker.sock \ 
# -v /home/romdon/development/projects/13/db_agent/backup:/usr/src/app/backup \ 
# 13angs/db-agent:latest

version: '3'

services:
  agent:
    image: 13angs/db-agent:${IMG_VERSION}
    build:
      context: .
      dockerfile: Dockerfile

    environment:
      - JOB_NAME=${JOB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_USER_PASSWORD=${DB_USER_PASSWORD}
      - DB_NAME=${DB_NAME}
      - BACKUP_PATH={BACKUP_PATH}
      - CONTAINER_NAME=${CONTAINER_NAME}

    # run a Docker image with additional groups for the user
    group_add:
      - ${ROOT_ID} # root
      - ${DOCKER_ID} # docker
    volumes:
      - backup_data:/usr/src/app/backup
      - restore_data:/usr/src/app/restore
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  backup_data:
    driver: local
    driver_opts:
      type: none
      device: ${DB_AGENT_BACKUP_DATA}
      o: bind

  restore_data:
    driver: local
    driver_opts:
      type: none
      device: ${DB_AGENT_RESTORE_DATA}
      o: bind
