# docker run --group-add 0 --group-add 1001 \
# -v /var/run/docker.sock:/var/run/docker.sock \ 
# -v /home/romdon/development/projects/13/db_agent/backup:/usr/src/app/backup \ 
# 13angs/db-agent:latest

version: '3'

services:
  agent:
    image: 13angs/db-agent:latest
    build:
      context: .
      dockerfile: Dockerfile
    
    # run a Docker image with additional groups for the user
    group_add:
      - '0' # root
      - '1001' # docker
    volumes:
      - ./backup:/usr/src/app/backup
      - /var/run/docker.sock:/var/run/docker.sock
  