version: '3'

services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
    volumes:
      - db_agent_volume:/var/lib/mysql
    networks:
      - default

  pma:
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=256M
    networks:
      - default

volumes:
  db_agent_volume:
    external: true
