name: db-agent-api

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'api/*'
  push:
    tags:
      - v*


jobs:

  build_and_push:
    name: Build/Test/Push to Docker Hub
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
        
      - name: Extract metadata (tags, labels) for docker
        id: meta
        uses: docker/metadata-action@v4
        with: 
          images: 13angs/db-agent-api

      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: ./api
          push: true
          tags: 13angs/db-agent-api:latest
          labels: ${{ steps.meta.outputs.labels }}