name: Docker Build

on:
  pull_request:
    branches: [ main ]

jobs:

  build_and_push:
    name: Build/Test/Push to Docker Hub
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        
      - name: Extract metadata (tags, labels) for docker
        id: meta
        uses: docker/metadata-action@v3
        with: 
          images: 13angs/db-agent

      - name: Build and push to Docker Hub
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: 13angs/db-agent
          tags: latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}